
_REF(Bullet,mDeadTime); 
_REF(Bullet,mSpeed); 
_REF(BulletEmiter,mBulletObject); 
_REF(DeltaTimeScale,mDeltaTimeScale); 
_REF(GetWeapon,mWeaponHand); 
_REF(GetWeapon,mGetParticle1); 
_REF(GetWeapon,mGetParticle2); 
_REF(MoveSmoke,mMaxSpeed); 
_REF(MoveSmoke,mSpeed); 
_REF(PlayerController,m_JumpPower); 
_REF(PlayerController,m_MoveSpeed); 
_REF(PlayerController,m_WeaponHand); 
_REF(TextureScroll,x); 
_REF(TextureScroll,y); 
_REF(TPSCamera,mDistance); 
_REF(TPSCamera,mUp); 
_REF(TPSCamera,mTarget); 
_REF(WeaponHand,m_GuardPos); 